#!/usr/bin/env python3
"""Regenerate CRITICALITY_METRICS.md from criticality_metrics.py's EXACT_METRICS /
APPROXIMATE_METRICS / NOT_APPLICABLE dicts, so the doc can never drift from the code.

Usage:
    python generate_applicability_doc.py
"""

from __future__ import annotations

from pathlib import Path

from criticality_metrics import APPROXIMATE_METRICS, EXACT_METRICS, NOT_APPLICABLE

OUT_PATH = Path(__file__).parent / "CRITICALITY_METRICS.md"

# Category membership, per the survey's own 8-way taxonomy (43 metrics total). Used only
# to group the tables below for readability; source of truth for status/reason stays the
# three dicts imported above.
CATEGORIES: list[tuple[str, list[str]]] = [
    (
        "Time-Scale (16)",
        ["ET", "PET", "PTTC", "PrET / SPrET / TA", "TET", "THW", "TIT", "TTB", "TTC",
         "TTCE", "TTS / TTK / TTR / generic TTM", "WTTC"],
    ),
    ("Distance-Scale (4)", ["AGS", "DCE", "HW", "PSD"]),
    ("Velocity-Scale (2)", ["CS (Conflict Severity)", "Delta-v"]),
    (
        "Acceleration-Scale (4)",
        ["DST (ts=0)", "DST (ts>0)", "a_lat,req / STN / LatJ", "a_long,req (DRAC)",
         "a_req (combined norm)"],
    ),
    ("Jerk-Scale (2)", ["LongJ"]),  # LatJ bundled under a_lat,req above
    (
        "Index-Scale (10)",
        ["ACI", "AM", "BTN", "CI (Conflict Index)", "CPI_deterministic", "PRI",
         "RSS_long_violation", "RSS-DS (full)", "SOI", "TCI"],
    ),
    ("Probability-Scale (3)", ["P-MC", "P-SMH", "P-SRS"]),
    ("Potential-Scale (2)", ["PF (Potential Functions)", "SP (Safety Potential / SFF)"]),
]


def _status(name: str) -> tuple[str, str]:
    if name in EXACT_METRICS:
        return "Exact", EXACT_METRICS[name]
    if name in APPROXIMATE_METRICS:
        return "Approximate", APPROXIMATE_METRICS[name]
    if name in NOT_APPLICABLE:
        return "Not applicable", NOT_APPLICABLE[name]
    return "?", "(not registered in criticality_metrics.py -- doc/code out of sync)"


def render() -> str:
    lines: list[str] = [
        "# Criticality metrics: applicability to the PufferDrive coordination pipeline",
        "",
        "Auto-generated by `generate_applicability_doc.py` from the `EXACT_METRICS` / "
        "`APPROXIMATE_METRICS` / `NOT_APPLICABLE` dicts in `criticality_metrics.py`. "
        "Re-run that script after editing those dicts -- do not hand-edit this file.",
        "",
        "Source survey: Westhofen, Neurohr, Koopmann et al. (2022), *Criticality Metrics "
        "for Automated Driving: A Review and Suitability Analysis of the State of the "
        "Art*, Archives of Computational Methods in Engineering. "
        "https://doi.org/10.1007/s11831-022-09788-7 (43 metrics across 8 categories).",
        "",
        f"**Summary: {len(EXACT_METRICS)} exact, {len(APPROXIMATE_METRICS)} approximate "
        f"(documented assumption), {len(NOT_APPLICABLE)} not applicable to this "
        "pipeline's state budget (ego + nearest-agent distance/closing-speed/TTC/speed, "
        "plus the policy's own discrete action distribution -- no lane geometry, no "
        "vehicle footprints/mass, no reaction-time model, no full multi-agent "
        "trajectories).**",
        "",
    ]

    for cat_name, metric_names in CATEGORIES:
        lines.append(f"## {cat_name}")
        lines.append("")
        lines.append("| Metric | Status | Notes |")
        lines.append("|---|---|---|")
        for name in metric_names:
            status, note = _status(name)
            lines.append(f"| {name} | {status} | {note} |")
        lines.append("")

    lines.append(
        "See `criticality_metrics.py` for the exact formula, citation, and "
        "implementation of every Exact/Approximate metric above."
    )
    return "\n".join(lines)


if __name__ == "__main__":
    OUT_PATH.write_text(render() + "\n")
    print(f"Wrote {OUT_PATH}")